
import Foundation

struct Tikers {
    
    static let symbols = [
//        "SPRT",
//        "BNTC",
//        "YVR",
//        "ODT",
//        "AMTX",
//        "ORMP",
//        "BIDU",
//        "MARA",
//        "APPN",
//        "IO",
//        "BRQS",
//        "VWAGY",
//        "RUN",
//        "TWST",
//        "MYSZ",
//        "TIGR",
//        "ZEAL",
//        "JD",
//        "DNMR",
//        "FUTU",
//        "MSFT",
//        "DFIFF",
//        "ATOS",
//        "RIOT",
//        "TKC",
//        "HCMC",
        "CLPS",
        "DOCU",
        "DOYU",
        "REGN",
        "LKNCY",
        "ZI",
        "AMC",
//        "DADA",
//        "RACE",
//        "AVEO",
//        "AZN",
//        "AMRS",
//        "APPS",
//        "BOXL",
//        "SHIP",
//        "BILI",
//        "SPWR",
//        "JBLU",
//        "VWAPY",
//        "UNP",
        "NMTR",
        "WKEY",
        "SNAP",
        "EBON",
        "W",
        "WATT",
        "CLSK",
        "BYND",
        "MRVL",
        "PLL",
        "AAPL",
        "AMZN",
        "TSLA",
        "GOOGL",
        "MSTR",
//        "BBBY",
//        "WWR",
//        "DVAX",
//        "AVGR",
//        "RIG",
//        "PM",
//        "AMAT",
//        "TOT",
//        "NCTY",
//        "TME",
        "ACB",
        "LULU"
    ]
}

